title: "Документация к проекту"
description: "Полная техническая документация"
baseurl: "" # если используется GitHub Pages в сабрепозитории — укажи "/repo-name"
url: "https://yourusername.github.io"

theme: minima
collections:
  pages:
    output: true
    permalink: /:path/

# Подключение навигации
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
