site_name: Datapulse
theme:
  name: material
  palette:
    scheme: slate  # <-- Это тёмная тема
  logo: images/white_logo.svg
extra_css:
  - css/custom.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
nav:
  - Главная: index.md
  - Что такое Datapulse?: invitation.md
  - Начало работы:
    - Установка: install.md
    - Первая модель: quickstart.md
  - Конструктор dbt:
      - Обзор: dbtmodel/overview.md
      - Работа с моделями dbt: dbtmodel/dbtmodel.md
      - Типы моделей dbt: dbtmodel/model_type.md
      - Больше возможностей: dbtmodel/extra_features.md
  - Конструктор DataVault:
      - Обзор: datavault/overview.md
      - Установка: datavault/install.md
      - Общая архитектура: datavault/architecture.md
      - Руководство:
          - Сущности: datavault/entity.md
          - Связи: datavault/link.md
          - Внесение изменений: datavault/changes.md
      - Граф: datavault/graph.md
      - Версионность: datavault/history.md
      - Суррогатные ключи: datavault/hash.md
  - Логирование: logs.md
  - Настройки: settings.md
  - Поддерживаемые СУБД: supported_db.md
